services:
  app:
    build: .
    container_name: de_pdm_container
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image : mysql:lts
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
