services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.web
    container_name: de_pdm_container
    env_file: ".env"
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./test:/app/tests
      - ./.devcontainer:/app/.devcontainer
      - ./pdm.lock:/app/pdm.lock
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    env_file: ".env"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
